version: '2'
services:
  db:
    image: mysql:5.6.26
    environment:
      MYSQL_ROOT_PASSWORD: $MYAPP_DATABASE_PASSWORD
  app:
    build: .
    environment:
      MYAPP_DATABASE_USERNAME: root
      MYAPP_DATABASE_PASSWORD: $MYAPP_DATABASE_PASSWORD
      MYAPP_DATABASE_HOST: db
      RAIL_ENV: development
  web:
    extends:
      service: app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  nginx:
    build: containers/nginx
    ports:
      - '8080:80'
    depends_on:
      - web
#  volumes:
#    db-data:
#      driver: local
